### ISSUE TITLE
Not work specific node version

### ISSUE THREAD

**Issue by sotayamashita** [sotayamashita/parse-migration-tool#1]
I got a error:

``` js
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

```
$ node -v
v0.12.3
$ npm -v
2.12.0
```

**Comment by sotayamashita** [comment]
Fix it
